// PRODUCT LIST TYPES
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';

// SINGLE PRODUCT
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAILED = 'PRODUCT_CREATE_REVIEW_FAILED';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST';
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS';
export const PRODUCT_TOP_FAILED = 'PRODUCT_TOP_FAILED';
// export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_DELETE_REVIEW_REQUEST = 'PRODUCT_DELETE_REVIEW_REQUEST';
export const PRODUCT_DELETE_REVIEW_SUCCESS = 'PRODUCT_DELETE_REVIEW_SUCCESS';
export const PRODUCT_DELETE_REVIEW_FAILED = 'PRODUCT_DELETE_REVIEW_FAILED';
export const PRODUCT_DELETE_REVIEW_RESET = 'PRODUCT_DELETE_REVIEW_RESET';


// CART
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
// export const CART_RESET_ITEMS = "CART_RESET_ITEMS";

// USER
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_FAILED = "USER_LIST_FAILED";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_RESET = "USER_LIST_SUCCESS";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_FAILED = "USER_DELETE_FAILED";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_FAILED = "USER_EDIT_FAILED";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_RESET = "USER_EDIT_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_FAILED = "USER_UPDATE_PROFILE_FAILED";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_UPDATE_DELIVERED_REQUEST = "USER_UPDATE_DELIVERED_REQUEST";
export const USER_UPDATE_DELIVERED_FAILED = "USER_UPDATE_DELIVERED_FAILED";
export const USER_UPDATE_DELIVERED_SUCCESS = "USER_UPDATE_DELIVERED_SUCCESS";
export const USER_UPDATE_DELIVERED_RESET = "USER_UPDATE_DELIVERED_RESET";

//ORDERS
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";

export const ORDER_FETCH_BY_ID_REQUEST = "ORDER_FETCH_BY_ID_REQUEST";
export const ORDER_FETCH_BY_ID_SUCCESS = "ORDER_FETCH_BY_ID_SUCCESS";
export const ORDER_FETCH_BY_ID_FAILED = "ORDER_FETCH_BY_ID_FAILED";

export const ORDER_PAY_RESET = "ORDER_PAY_RESET";
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAILED = "ORDER_PAY_FAILED";

export const ORDER_LIST_PROFILE_REQUEST = "ORDER_LIST_PROFILE_REQUEST";
export const ORDER_LIST_PROFILE_SUCCESS = "ORDER_LIST_PROFILE_SUCCESS";
export const ORDER_LIST_PROFILE_FAILED = "ORDER_LIST_PROFILE_FAILED";
export const ORDER_LIST_PROFILE_RESET = "ORDER_LIST_PROFILE_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILED = "ORDER_LIST_FAILED";
